config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN:
      branch: main
      repo: https://github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN
      subfolder: DTC74/WF7401/ST740102/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-turquoise-sloth.sh
        container: qc.acc_skinny-cream-monkey
  QC.Doc:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-yellow-sheepdog.sh
        container: qc.doc_leaky-cornflower-flamingo
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-chartreuse-wasp.sh
        container: qc.doc_gimpy-cornflower-fossa
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-bistre-wrasse.sh
        container: qc.doc_queasy-viridian-hyena
  QC.Lic:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-harlequin-serval.sh
        container: qc.lic_fuzzy-chestnut-coati
  QC.Ver:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-persimmon-crab.sh
        container: qc.ver_snoopy-vermilion-dalmatian
timeout: 5400
