config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN:
      branch: main
      repo: https://github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN
      subfolder: DTC74/WF7401/ST740102/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-azure-kudu.sh
        container: qc.acc_fuzzy-denim-dragonfly
  QC.Doc:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-persimmon-forest.sh
        container: qc.doc_craggy-crimson-akbash
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-bistre-stingray.sh
        container: qc.doc_hazy-alizarin-chinook
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-brass-spider.sh
        container: qc.doc_sleepy-lemon-chamois
  QC.Lic:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-black-eleuth.sh
        container: qc.lic_sleazy-red-tarantula
  QC.Ver:
    repos:
      github.com/NicoSchlw/run_dynamic_source_inversion_FD3D_TSN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-azure-centipede.sh
        container: qc.ver_clammy-tangerine-meerkat
timeout: 5400
